Bundles\CallMeBundle\Entity\CallMe:
    type: entity
    table: call_me
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        object:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        type_message:
            type: string
            length: 255
            nullable: true
        message:
            type: text
            length: 1024
            nullable: true
        done:
            type: boolean
#    manyToOne:
#        client:
#            targetEntity: Bundles\UserBundle\Entity\Client
#            joinColumn:
#                name: client_id
#                referencedColumnName: id
    lifecycleCallbacks: {  }
