Bundles\CallMeBundle\Entity\Trip:
    type: entity
    table: trip
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        dispatch:
            type: string
            length: 255
        destination:
            type: string
            length: 255
        date_travel:
            type: date
        services:
            type: string
            length: 255
            nullable: true
        quantity_people:
            type: integer
            nullable: true
        phone:
            type: string
            length: 255
        email:
            type: string
            length: 255
        done:
            type: boolean
    lifecycleCallbacks: {  }
