<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="robots" content="noindex">
<?php
if (\Core\Security\OwnerService::instance()->hasBusinessEdition()&&
    \Component\Branding\Model\Branding::tableExists()) {
    $favicon = \Component\Branding\Repository\BrandingRepository::instance()->getFavicon();
    if (!empty($favicon)) {
        echo "<link rel='shortcut icon' type='image/x-icon' href='{$favicon}'/>";
    }
}
if (\Core\Application\Application::instance()->isProduction()) {
    echo $this->wrapCss('assets/vendor.css');
}
?>
