<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title>Something wrong...</title>
    <?php include 'shared/_head.phtml' ?>
    <?php
    if (\Core\Application\Application::instance()->isProduction()) {
        echo $this->wrapCss('assets/app.css');
    }
    ?>
</head>
<body>
    <div class="container">
        <div class="col-md-4 col-md-offset-4 error-block">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php echo $content ?>
                </div>
            </div>
        </div>
    </div>
    <script type="application/javascript"> var kData = {}; var kTranslations = {}; </script>
    <?php include 'shared/_footer.phtml' ?>
</body>
</html>
