<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title><?php echo $this->getTitle() ?></title>
    <?php include 'shared/_head.phtml' ?>
    <?php
    if (\Core\Application\Application::instance()->isProduction()) {
        echo $this->wrapCss('assets/app.css');
    }
    ?>
    <script>var kData = {}; var kTranslations = {}</script>
</head>
<body>
    <div class="container">
        <div class="col-md-5 col-md-offset-2 error-block <?php echo (isset($this->alert)) ? $this->alert : '' ?>">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php echo $content ?>
                </div>
            </div>
        </div>
    </div>
    <?php include 'shared/_footer.phtml' ?>
</body>
</html>
